# =========================================================
# AnyBase Kernel 自定义外部模块配置文件
# =========================================================

# 模块基础信息
module_id="redmi_turbo4pro_modifier"
module_name="Redmi Turbo 4 Pro LTO & SUSFS Fixer"
module_author="2275"
module_version="1.0.0"
module_description="强制关闭内核LTO优化，完整保留符号表，完美修复SukiSU隐藏SELinux功能"

# 框架执行生命周期设定
# 告诉 AnyBase 在内核正式编译前（Pre-Build）执行我们的 setup.sh
run_stage="pre_build"
script_file="setup.sh"
